---
sidebar: sidebar 
permalink: task_cli_deploy_image_add.html 
keywords: administer, administering, cli, deploy, ontap select image, add 
summary: 'Vous pouvez ajouter une image ONTAP Select à votre instance de l"utilitaire d"administration Deploy. Une fois l"image installée, vous pouvez l"utiliser lors du déploiement d"un cluster ONTAP Select.' 
---
= Ajoutez une image ONTAP Select à déployer
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez ajouter une image ONTAP Select à votre instance de l'utilitaire d'administration Deploy. Une fois l'image installée, vous pouvez l'utiliser lors du déploiement d'un cluster ONTAP Select.



== Avant de commencer

De manière générale, le processus utilisé pour ajouter une image ONTAP Select à une instance de Deploy se compose de quatre étapes :

. Téléchargement de l'image d'installation
. Téléchargement de l'image d'installation sur la machine virtuelle Deploy
. Ajout de l'image d'installation
. Affichage des images d'installation disponibles


Avant d'ajouter de nouvelles images ONTAP Select à déployer, vous devez d'abord supprimer les images inutiles.


NOTE: Vous ne devez ajouter qu'une image ONTAP Select avec une version antérieure à la version d'origine incluse avec votre instance de l'utilitaire de déploiement. L'ajout des dernières versions de ONTAP Select, disponibles auprès de NetApp, n'est pas pris en charge.



== Téléchargez l'image d'installation

Pour commencer à ajouter une image ONTAP Select à une instance de l'utilitaire de déploiement, vous devez télécharger l'image d'installation à partir du site de support NetApp. L'image d'installation de ONTAP Select est formatée sous forme de fichier compressé unique.

.Étapes
. Accédez au site d'assistance NetApp à l'aide d'un navigateur web et cliquez sur *Support Quick Links*.
. Cliquez sur *Download Software* sous *Top Tasks* et connectez-vous au site.
. Cliquez sur *Find your product*.
. Faites défiler vers le bas et cliquez sur *ONTAP Select*.
. Sous *Other Available Select Software*, cliquez sur *Deploy Upgrade, Node Upgrade, Image Install*.
. Sélectionnez la version souhaitée du package de mise à niveau.
. Examinez le contrat de licence utilisateur final (CLUF) et cliquez sur *Accepter et continuer*.
. Sélectionnez et téléchargez le package approprié, en répondant à toutes les invites selon les besoins de votre environnement.




== Téléversez l'image d'installation sur Deploy

Après avoir acquis l'image d'installation de ONTAP Select, vous devez charger le fichier sur la machine virtuelle de déploiement.

.Avant de commencer
Vous devez disposer du fichier image d'installation sur votre poste de travail local. Vous devez également avoir le mot de passe du compte utilisateur administrateur Deploy.

.Description de la tâche
Cette tâche décrit une méthode de téléchargement du fichier sur la machine virtuelle de déploiement. D'autres options peuvent être plus adaptées à votre environnement.

.Étape
. Dans une invite de commandes sur votre poste de travail local, téléversez le fichier image sur la machine virtuelle Deploy.
+
Exemple

+
....
scp image_v_93_install_esx.tgz admin@10.234.81.101:/home/admin (provide password when prompted)
....
+
Exemple

+
....
sftp admin@10.234.81.101 (provide password when prompted)
put image_v_93_install_esx.tgz
exit
....


.Résultat
Le fichier d'installation du nœud est stocké dans le répertoire personnel de l'utilisateur admin.



== Ajouter l'image d'installation

Vous pouvez ajouter l'image d'installation ONTAP Select au répertoire des images de Deploy afin qu'elle soit disponible lors du déploiement d'un nouveau cluster.

.Avant de commencer
Vous devez savoir dans quel répertoire le fichier image d'installation a été placé sur la machine virtuelle de l'utilitaire de déploiement. Il est supposé que le fichier se trouve dans le répertoire personnel de l'administrateur.

.Étapes
. Connectez-vous à l'interface de ligne de commande de l'utilitaire de déploiement à l'aide de SSH avec le compte administrateur (admin).
. Démarrer la coque de Bash :
+
`shell bash`

. Placez le fichier image d'installation dans le répertoire images.
+
Exemple
`tar -xf image_v_93_install_esx.tgz -C /opt/netapp/images/`





== Afficher les images d'installation disponibles

Vous pouvez afficher les images ONTAP Select disponibles lors du déploiement d'un nouveau cluster.

.Étapes
. Accédez à la page Web de documentation en ligne à l'aide de la machine virtuelle de l'utilitaire de déploiement et connectez-vous à l'aide du compte administrateur (admin) :
+
`\http://<FQDN|IP_ADDRESS>/api/ui`

+
Utilisez le nom de domaine ou l'adresse IP de la machine virtuelle de déploiement.

. Accédez au bas de la page et cliquez sur *Deploy* puis sur *GET /images*.
. Cliquez sur *Essayez-le !* pour afficher les images ONTAP Select disponibles.
. Vérifiez que l'image souhaitée est disponible.

